#Author: alex sun
#Date: 05312021
#Desc: prepare data for training
#rev date: 04132023, cleanup 
#============================================================
#third party imports
import torch
from torch.utils.data import TensorDataset, Dataset
import pandas as pd
import numpy as np
from timeit import default_timer
import pickle as pkl
import matplotlib.pyplot as plt
from scipy import stats
import os

#from this code repo
from genrivernet import loadWatershed
from nwmutils import getUSGSData
from util_gtnet import toTensor, load_config

device = 'cuda' if torch.cuda.is_available() else 'cpu'

def formAdjacencyMat(rootDir,watershed,goodIDSet,comIDdict,isWeighting=False,isDirected=False, 
                     add_self_loop=False, plotting=False,connect_exta_path=False,watershedtype=1,
                     nwm_ver='2.0'):
    """Form adjacency mat using ONLY valid nodes
    Params
    ------
    rootDir,
    watershed, name of the watershed
    goodIDSet, id set of valid nodes
    """
    #hack to deal with different national water model version
    if nwm_ver=='2.0':
        adjfile = os.path.join(rootDir, 'data/{0}/adjinfo.pkl'.format(watershed))
    else:
        adjfile = os.path.join(rootDir, 'data/{0}/adjinfo{1}.pkl'.format(watershed,nwm_ver))
    #note the following info is on the whole node set. It's generated by genrivernet.py
    resDict = pkl.load(open(adjfile, 'rb'))
    num_nodes = resDict['num_nodes']
    startNode = resDict['start_node'] 
    endNode   = resDict['end_node']
    if watershedtype==1:
        #for fpp watershed, there's no edge length attr
        edgeLen   = resDict['edge_len']
    else:
        isWeighting=False
    if connect_exta_path:
        #Experimental feature, doesn't work well, so it's disabled by default
        print ('ADDING extra paths to adj mat ')
        for item in resDict['extra_path_nodes']:
            startNode.append(item[0])
            endNode.append(item[1])

    #!!!!Warning: this dense mat needs to be replaced by sparse mat for large arrays
    A = np.zeros((num_nodes,num_nodes))
    #
    #Constructed graph and add self loop (only if add self loop is true)
    #    
    if isWeighting:        
        imethod = 1
        #use the inverse distance as weight
        if imethod==1:
            #normalize edgeLen first
            edgeLen = 1.0/np.array(edgeLen)
            edgeLen = (edgeLen-np.min(edgeLen))/(np.max(edgeLen)-np.min(edgeLen))
            for i in range(len(startNode)):            
                A[startNode[i],endNode[i]] = edgeLen[i]
                if not isDirected:            
                    A[endNode[i],startNode[i]] = A[startNode[i],endNode[i]]               
        else:
            #this is Xiaowei's exp weighting method
            sigma2 = (np.std(edgeLen))**2 
            #edgeLen = edgeLen(np.nanmax(edgeLen))
            for i in range(len(startNode)):            
                dij = np.exp(-0.5*edgeLen[i]*edgeLen[i]/sigma2)
                A[startNode[i],endNode[i]] = dij #if dij>=0.5 else 0
                if not isDirected:
                    A[endNode[i],startNode[i]] = A[startNode[i],endNode[i]]        
            print ('sigma2',sigma2, np.nanmax(A))
    else:
        #unweighted undirected river distances
        for i in range(len(startNode)):
            A[startNode[i],endNode[i]] = 1.0
            if not isDirected:            
                A[endNode[i],startNode[i]] = 1.0   
            
    #Remove all isolated nodes
    A = A[goodIDSet,:][:,goodIDSet]

    #add self loop
    if add_self_loop:
        np.fill_diagonal(A,1.0)
    else:
        np.fill_diagonal(A,0.0)

    if plotting:
        fig,ax=plt.subplots(1,1)
        ax.matshow(A)
        plt.savefig('outputs/testadj_{0}.png'.format(watershed))
        plt.close()
    
    return A

def convertFPP2NodeIndex(comIDdict,fpplist):
    """Find the node index relative to goodIDset
    This is only used by the graph coarsening experiment
    Note: if basin not in the good comid set, it is dropped
    """
    #column order in Adj is the same as goodIDSet, 
    #so find the position of fpplist relative to goodIDSet
    #use the mapping stored in comIDdict
    fpp_node_pos=[]
    for comid in fpplist:
        if comid in comIDdict.keys(): 
            fpp_node_pos.append(comIDdict[comid])
    return fpp_node_pos

def loadNWMDF(args):
    """Load river reach information from the NHD+ database
    """
    return loadWatershed(args)
    
def getStandardScaler(forcingDict, dfQ,trainLen,logTran=False):
    """
    dfAll, collated DF of all comIDs along the time dimension
    """

    bigDF = []
    for item in forcingDict.keys():
        bigDF.append(forcingDict[item].iloc[:trainLen,:])
    bigDF=pd.concat(bigDF, axis=0) #NT x NForcing
    
    input_means = np.nanmean(bigDF.to_numpy(), axis=0)
    input_stds = np.nanstd(bigDF.to_numpy(), axis=0)    

    bigDF = None

    #get sample mean
    if logTran:
        print ('doing log transform')
        bigQ = dfQ.to_numpy(copy=True)[:trainLen,:]   
        q_scale = 5.0
        bigQ = np.log(bigQ+1e-4)/q_scale
        #these stats are not needed for logtran
        output_mean = np.nanmean(bigQ,axis=0) 
        output_std = np.nanstd(bigQ,axis=0)
    else:
        bigDF = None
        bigQ = dfQ.to_numpy()[:trainLen,:]
        output_mean = np.nanmean(bigQ,axis=0)
        output_std = np.nanstd(bigQ,axis=0)

    myscaler = {
        'input_means': input_means,
        'input_stds': input_stds,
        'output_mean': output_mean,
        'output_std': output_std,
    } 
    if logTran:
        #store the scaler for later use
        myscaler['q_scale'] = q_scale

    return myscaler

def removeAttrFromForcingSet(forcingDFDict, attr):
    """Remove certain attribute from forcingDF
    """
    all_attr = ['prcp','srad','swe','tmax','tmin','vp']
    #remove the attr from all_attr
    all_attr = list(set(all_attr)-set([attr]))
    print ('new forcing set', all_attr)
    for item in forcingDFDict.keys():
        forcingDFDict[item] = forcingDFDict[item].loc[:,all_attr]
    return forcingDFDict

def genMLDataSetsWithForcing(watershed,in_dim,comIDSet,forcingDFDict,allDF,noffset,
        outputdir,trainRatio=(0.7,0.15),
        logTran=True,
        addStatics=False,
        addNWM=False,
        allDF_obs=None, 
        dumping=False, 
        useCustomDataset=False,
        removeSWE=False,
        trainEndDate=None,
        valEndDate=None):   
    """Assemble dataset for GNN training/testing

    Parameters
    ----------
    watershed, name of the watershed
    in_dim, input feature dimension
    comIDSet, a subset of comID's used in the network
    forcingDFDict, dictionary of forcing dataframes for all comID's (dict key is comID)
    allDF,  dataframe of nwm-simulated flowrates    
    noffset, the offset to be used (i.e., look seq length)
    logTran, true to transform streamflow data (default False)
    addStatics, true to add static features to the ML mat (default False)
    addNWM, true to use NWM data as input (default None)
    dumping, true to dump the dataset files (default False)
    allDF_obs, allDF_obs contains labeled data at gage locations; used for fine-tuning 

    Returns
    -------
    trainDataset,valDataset,testDataset, datasets for ML
    nfeatures, number of input features
    """ 
    def getNormalFeature(df,vartype='input',logTran=False):
        #this should do feature-wise normalization
        if vartype=='input':
            return (df.to_numpy()-myscaler['input_means'])/myscaler['input_stds']
        else:
            if logTran:
                return np.log(df.to_numpy()+1e-4)/myscaler['q_scale']
            else:
                return (df.to_numpy()-myscaler['output_mean'])/myscaler['output_std']
    
    #allDF_obs contains labeled data at gage locations
    #if it's none, replicate using nwm data
    if allDF_obs is None:
        allDF_obs = allDF.copy()
    if  removeSWE:
        #remove snow water equivalent from forcing [For Houston we don't need snow]
        #this is only necessary for daymet data
        forcingDFDict = removeAttrFromForcingSet(forcingDFDict, attr='swe')

    
    #split time period into training and validation periods
    #@todo: maybe a random split is more reasonable?
    if trainEndDate is not None and valEndDate is not None:
        #explicit date-based split, overrides trainRatio
        trainLen = allDF.index.searchsorted(pd.Timestamp(trainEndDate)) + 1
        valEnd   = allDF.index.searchsorted(pd.Timestamp(valEndDate)) + 1
        valLen   = valEnd - trainLen
        print(f'date-based split: train ends {allDF.index[trainLen-1].date()} ({trainLen} days), '
              f'val ends {allDF.index[valEnd-1].date()} ({valLen} days), '
              f'test is remaining {allDF.shape[0]-valEnd} days')
    else:
        trainLen = int(trainRatio[0]*allDF.shape[0])
        valLen   = int(trainRatio[1]*allDF.shape[0])
    
    myscaler = getStandardScaler(forcingDFDict,allDF,trainLen,logTran)
    starttime= default_timer()
    if addStatics:
        staticarr = pkl.load(open('data/{0}/staticdata.pkl'.format(watershed), 'rb'))
        nfeaturesd = in_dim if addNWM else in_dim-1
        if removeSWE:
            nfeaturesd-=1
        if len(staticarr.shape)>1:
            nfeatures = nfeaturesd+staticarr.shape[1] #forcing+NWM & static features
        else:
            nfeatures = nfeaturesd+1 
            staticarr = staticarr[:,np.newaxis]
    else:            
        # no of forcing plus Q if addNWM
        nfeatures = in_dim  if addNWM else in_dim-1

        if removeSWE:
            nfeatures-=1

    #do transform on the entire comid set
    if logTran:
        outmat = getNormalFeature(allDF,vartype='output',logTran=logTran)
        outmat_obs = getNormalFeature(allDF_obs,vartype='output',logTran=logTran)
    else:
        outmat = getNormalFeature(allDF,vartype='output')
        outmat_obs = getNormalFeature(allDF_obs,vartype='output')
        
    inNorm={}
    outNorm={}
    outNorm_obs={}
    #this ensures the same node order as in allDF
    for ix,comID in enumerate(comIDSet): 
        #normalize the features and save to dictionaries            
        inmat  = getNormalFeature(forcingDFDict[comID],vartype='input')
        inNorm[comID] = inmat
        outNorm[comID] = outmat[:, ix] #a vector
        outNorm_obs[comID] = outmat_obs[:,ix] #a vector

    #==== MEMORY FIX: preallocate final arrays instead of Python lists + np.asarray ====
    #(the previous approach built per-day arrays in Python lists, then called np.asarray()
    # at the end, which briefly holds BOTH the list and the new array in memory at once --
    # roughly doubling peak memory. Preallocating and writing by index avoids that.)
    n_train = max(0, trainLen - noffset)
    n_val   = valLen
    n_test  = allDF.shape[0] - trainLen - valLen
    nnodes  = allDF.shape[1]
    print(f'preallocating tensors: train={n_train} val={n_val} test={n_test} '
          f'(nodes={nnodes}, nfeatures={nfeatures}, seq={noffset})')

    Xtrain = np.zeros((n_train, noffset, nnodes, nfeatures), dtype=np.float32)
    ytrain = np.zeros((n_train, nnodes), dtype=np.float32)
    Xval   = np.zeros((n_val,   noffset, nnodes, nfeatures), dtype=np.float32)
    yval   = np.zeros((n_val,   nnodes), dtype=np.float32)
    Xtest  = np.zeros((n_test,  noffset, nnodes, nfeatures), dtype=np.float32)
    ytest  = np.zeros((n_test,  nnodes), dtype=np.float32)

    i_train = i_val = i_test = 0
    #iterate through time steps 
    # daymet: 'prcp (mm/day)', 'srad (W/m^2)', 'swe (kg/m^2)', 'tmax (deg c)', 'tmin (deg c)', 'vp (Pa)'
    # nldas: 'apcpsfc (kg/m^2)', 'dlwrfsfc (W/m^2)', 'dswrfsfc (W/m^2)', 'spfh2m (kg/kg)', 'tmp2m (K)'
    # aorc:  'apcpsfc (kg/m^2)' 'tmp2m (K)' see https://hydrology.nws.noaa.gov/aorc-historic/Documents/AORC-Version1.1-SourcesMethodsandVerifications.pdf
    # note kg/m^2 == mm
    for irow in range(noffset, allDF.shape[0]):            
        if irow<trainLen:
            featureMat = Xtrain[i_train]
            targetvec  = ytrain[i_train]
            i_train += 1
        elif irow<trainLen+valLen:
            featureMat = Xval[i_val]
            targetvec  = yval[i_val]
            i_val += 1
        else:
            featureMat = Xtest[i_test]
            targetvec  = ytest[i_test]
            i_test += 1

        for inode,comID in enumerate(comIDSet):                
            if addStatics:
                if addNWM:
                    featureMat[:,inode,:nfeaturesd-1] = inNorm[comID][irow-noffset:irow,:]                
                    featureMat[:,inode,nfeaturesd] = outNorm[comID][irow-noffset:irow]
                else:
                    featureMat[:,inode,:nfeaturesd] = inNorm[comID][irow-noffset:irow,:]                
                #repeat static data for each day
                featureMat[:,inode,nfeaturesd:] = staticarr[inode,:][np.newaxis,:].repeat(noffset,axis=0)
            else:
                if addNWM:   
                    featureMat[:,inode,:-1] = inNorm[comID][irow-noffset:irow,:]                
                    featureMat[:,inode,-1]  = outNorm[comID][irow-noffset:irow]
                else:
                    featureMat[:,inode,:] = inNorm[comID][irow-noffset:irow,:]

            #form target vector, size=[nnode]
            targetvec[inode] = outNorm_obs[comID][irow]

    print ('Time taken to form input data', default_timer()-starttime)
    if logTran:
        saved_file = os.path.join(outputdir, 'mldataf_log.pkl')
        outscalername = 'myscaler_log.pkl'
    else:
        saved_file = os.path.join(outputdir, 'mldataf.pkl')
        outscalername = 'myscaler.pkl'
    pkl.dump(myscaler, open(f'{outputdir}/{outscalername}', 'wb'))
    if dumping:
        #save the data
        pkl.dump([Xtrain,ytrain,Xval,yval,Xtest,ytest], open(saved_file, 'wb'))
    
    ##format train/val/test datasets
    #training
    Xin = torch.from_numpy(Xtrain)
    y  =  torch.from_numpy(ytrain)
    print ('train data shape', Xin.shape, y.shape)
    if useCustomDataset:
        trainDataset = MyTensorDataset(Xin,y)
    else:
        trainDataset = TensorDataset(Xin,y)
    #validation
    Xin = torch.from_numpy(Xval)
    y  =  torch.from_numpy(yval)
    if useCustomDataset:
        valDataset = MyTensorDataset(Xin,y)
    else:
        valDataset = TensorDataset(Xin,y)
    print ('val data shape', Xin.shape, y.shape)

    #testing
    Xin = torch.from_numpy(Xtest)
    y  =  torch.from_numpy(ytest)
    if useCustomDataset:
        testDataset = MyTensorDataset(Xin,y)
    else:
        testDataset = TensorDataset(Xin,y)
    print ('test data shape', Xin.shape, y.shape)
    nfeatures = Xin.shape[-1]
    return trainDataset,valDataset,testDataset,nfeatures

def loadFPPSet(args):
    """Load a set of huc12 pour points from network for graph coarsening
    """
    import geopandas as gpd
    nhdplusdbroot = args.nhdplusdbroot
    wobj = loadWatershed(args,returnWobj=True)
    #get name of fpp shpfile
    if not wobj.fppshp is None and os.path.exists(wobj.fppshp):
        gdf = gpd.read_file(wobj.fppshp)
        print ('load fpp for ', wobj.watershed)
        #get a list of comids
        fpplist = gdf[wobj.comIDColName].tolist()
        if not wobj.fppreplacement is None:
            #do replacement
            fpplist_m = []
            for item in fpplist:
                if item in wobj.fppreplacement.keys():
                    fpplist_m.append(wobj.fppreplacement[item])
                else:
                    fpplist_m.append(item)
            return sorted(fpplist_m)
        else:
            return sorted(fpplist)
    else:
        raise Exception('fpp not found for ', args.watershed_name)


class MyTensorDataset(Dataset):
    """TensorDataset with support of transforms.
    """
    def __init__(self, *tensors):
        assert all(tensors[0].size(0) == tensor.size(0) for tensor in tensors)
        self.tensors = tensors

    def __getitem__(self, index):
        return tuple(tensor[index] for tensor in self.tensors),index

    def __len__(self):
        return self.tensors[0].size(0)

def imshow(img, title=''):
    """Plot the image batch.
    """
    plt.figure(figsize=(10, 10))
    plt.title(title)
    plt.imshow(np.transpose( img.numpy(), (1, 2, 0)), cmap='gray')
    plt.show()

def main():
    import argparse
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description="Parse arguments for genrivernet",
    )
    parser.add_argument('--config', type=str, required=True, help='config file name')
    cargs = parser.parse_args()
    
    args = load_config(cargs.config)
    watershed = args.watershed_name 
    comIDset,comIDdict,allDF,goodInd,gageDict = loadNWMDF(args)    

    
    formAdjacencyMat(args.rootdir, 
                     watershed=watershed,comIDdict=comIDdict,
                     goodIDSet=goodInd, 
                     plotting=args.network.plotadj,
                     isWeighting=args.network.weighted_adj,
                     nwm_ver=args.data.nwm_ver)
    
    #map gage comid to node index
    gageNodeInd=[]
    for item in gageDict.keys():
        try:
            #do reverse lookup
            gageNodeInd.append(comIDdict[item])
        except:
            pass
    print ('adj mat index of the observation nodes', gageNodeInd)
    
    #
    #=====Get USGS obs data (set reLoad to True if calling for first time) ===========
    #
    #for 3H data [this is not working for daymet]
    assert (args.data.interval in ['3H', '24H'])
    if args.data.interval=='3H':
        usgsDataDict = getUSGSData(watershed=watershed, gageIDset=gageDict.values(),
                       reLoad=args.data.reload_usgs, valueType='iv')
    else:
        #for 1d data
        usgsDataDict = getUSGSData(watershed=watershed, gageIDset=gageDict.values(),
                       reLoad=args.data.reload_usgs, valueType='dv')
    #this is the lookback period
    noffset = args.data.seq_length
    outputdir = os.path.join(args.rootdir, 'data/{0}'.format(watershed))

    #========Select different forcing data soruce =============
    if args.data.forcing_source in ['daymet', 'Daymet']:
        forcingDF = pkl.load(open('data/{0}/daymetforcing{1}_nwm{2}.pkl'.format(watershed, len(comIDset), args.data.nwm_ver),'rb'))
        in_dim = 7 #for daymet (6 forcing vars + Q), if removeSWE then in_dim will be reduced by 1 
        removeSWE = args.data.removeSWE
    elif args.data.forcing_source in ['nldas', 'NLDAS']:       
        forcingDF = pkl.load(open('data/{0}/nldasforcing{1}_nwm{2}_{3}.pkl'.format(watershed, len(comIDset), args.data.nwm_ver, args.data.interval),'rb'))
        in_dim = 6 #for nldas  (5 forcing vars + Q)
        removeSWE = False
    elif args.data.forcing_source in ['aorc', 'AORC']:
        forcingDF = pkl.load(open('data/{0}/aorcforcing{1}_nwm{2}_{3}.pkl'.format(watershed, len(comIDset), args.data.nwm_ver, args.data.interval),'rb'))
        in_dim = 3 #for aorc (2 forcing vars + Q)
        removeSWE = False
    elif args.data.forcing_source in ['era5', 'ERA5']:
        forcingDF = pkl.load(open('data/{0}/era5forcing_full_nwm{1}_{2}.pkl'.format(watershed, args.data.nwm_ver, args.data.interval),'rb'))
        in_dim = 9  # 8 ERA5 vars + Q
        removeSWE = False
    else:
        raise ValueError("Invalid forcing source ")
    
    #align allDF's date range to match the forcing data's actual coverage
    #(streamflow and forcing pickles were built from different source-year ranges,
    # so row i in allDF is not guaranteed to be the same date as row i in forcingDF)
    _sample_comid = next(iter(forcingDF.keys()))
    _forcing_start = forcingDF[_sample_comid].index.min()
    _forcing_end   = forcingDF[_sample_comid].index.max()
    print(f'forcing date range: {_forcing_start.date()} to {_forcing_end.date()}')
    print(f'allDF date range before align: {allDF.index.min().date()} to {allDF.index.max().date()} ({allDF.shape[0]} days)')
    allDF = allDF.loc[_forcing_start:_forcing_end]
    print(f'allDF date range after align:  {allDF.index.min().date()} to {allDF.index.max().date()} ({allDF.shape[0]} days)')
    for _c in comIDset:
        assert len(forcingDF[_c]) == allDF.shape[0], f'row count mismatch for comid {_c}: forcing={len(forcingDF[_c])} allDF={allDF.shape[0]}'

    #========Generate datasets ====================
    genMLDataSetsWithForcing(watershed,in_dim,comIDset,forcingDF,allDF,noffset,outputdir,
            trainRatio=(0.7,0.15),
            logTran=args.data.uselog,
            addStatics=args.data.addstatics,
            addNWM=args.data.addnwm,
            removeSWE= removeSWE,
            trainEndDate='2010-12-31',
            valEndDate='2015-12-31')


if __name__ == '__main__':
    main()